services:
  bd:
    image: docker.io/vinilmt/vestigium_bd:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vestigium
    ports:
      - "5432:5432"

  backend:
    image: docker.io/vinilmt/vestigium_backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres@bd:5432/vestigium
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - bd

  frontend:
    image: docker.io/vinilmt/vestigium_frontend:latest
    environment:
      API_URL: http://localhost:8000
    ports:
      - "8080:80"
    depends_on:
      - backend
